server:
  port: 80

spring:
  application:
    name: cloud-cunsumer-order80
  devtools:
    livereload:
      port: 35730
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: order80
    prefer-ip-address: true

