#####################
# 需要修改host文件 增加127.0.0.1  config-3344.com
#####################

server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:wayn111/springcloud-learning-2020.git #github上仓库地址
          search-paths:
            # 搜索目录
            - springcloud-learning-2020
          timeout: 30
          default-label: main
      # 配置默认分支
      label: main
  # 配置rabbitmq
  rabbitmq:
    host: wayn.ltd
    port: 5672
    username: guest
    password: guest

#服务注册到Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka


# 全局动态刷新给configServer发送： curl -X POST "http://localhost:3344/actuator/bug-refresh"
# 局部动态刷新给configServer发送： curl -X POST "http://localhost:3344/actuator/bug-refresh/config-client:3355"
management:
  endpoints:
    web:
      exposure:
        include: "*"
