server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  devtools:
    livereload:
      port: 35729
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 # 采样率设置，介于0-1之间，1表示全部采集
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://waynmysql.mysql.rds.aliyuncs.com:3306/spring_cloud_learning?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: wayn
    password: heGE@@201011
    druid:
      validation-query: select 1

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.wayn.learn.springcloud.payment.entity

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 1 # 向eureka发送心跳的间隔时间
#    lease-expiration-duration-in-seconds: 2 # eureka连接超时检测，超出指定时间则会剔除服务

