server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment8001
  devtools:
    livereload:
      port: 35729
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://waynmysql.mysql.rds.aliyuncs.com:3306/spring_cloud_learning?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: wayn
    password: heGE@@201011
    druid:
      validation-query: select 1

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.wayn.learn.springcloud.payment.entity
