server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  devtools:
    livereload:
      port: 35729
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://waynmysql.mysql.rds.aliyuncs.com:3306/spring_cloud_learning?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: wayn
    password: heGE@@201011
    druid:
      validation-query: select 1

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.wayn.learn.springcloud.payment.entity

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8002
    prefer-ip-address: true
