server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   # 使用注册中心的微服务名
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            - Method=POST,GET  # 请求方法类型匹配
            - Query=color,gree. # 请求参数匹配color为name，gree.是value，.代表匹配任意字符
            - Cookie=chocolate, ch.p # 请求cookie匹配，cookie中包含key为chocolate，value为ch.p
            - Header=X-Request-Id, \d+ # 请求头匹配，请求头key为X-Request-Id，value为数字
        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lbGet   #断言,路径相匹配的进行路由
            - After=2021-06-22T22:02:04.867+08:00[Asia/Shanghai] # 在指定时间后才能匹配
      discovery:
        locator:
          enabled: true # 启动从注册中心利用微服务名称进行动态路由的功能

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


