server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版

#ribbon的超时时间
ribbon:
  ReadTimeout: 500 # 建立连接所需时间
  ConnectTimeout: 500 # 建立连接后，从服务端读取数据所需时间

logging:
  level:
    com.wayn.learn.springcloud.feign.service.PaymentFeignService: debug # 开启feign日志打印
